<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // HAPUS SEMUA DATA
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('cars')->truncate();
        DB::table('data_user')->truncate();

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // BUAT USER ADMIN
        DB::table('data_user')->insert([
            [
                'name' => 'Admin',
                'email' => 'admin@rentcar.com',
                'password' => Hash::make('admin123'),
                'role' => 'admin',
                'status_login' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'User Demo',
                'email' => 'user@rentcar.com',
                'password' => Hash::make('user123'),
                'role' => 'user',
                'status_login' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // DATA MOBIL BERDASARKAN GAMBAR
        $cars = [
            [
                'brand' => 'Toyota',
                'model' => 'Camry',
                'category' => 'Sedan',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 5,
                'doors' => 4,
                'year' => 2023,
                'engine' => '2.5L DOHC',
                'price_per_day' => 450000,
                'reduce' => 10,
                'police_number' => 'B 1234 ABC',
                'image' => '/storage/cars/Toyota_Camry.jpg',
                'status' => 'tersedia',
                'stars' => 4.8,
                'minimum_rental_days' => 1,
                'description' => 'Toyota Camry adalah sedan mewah dengan performa tinggi dan kenyamanan maksimal.',
                'color' => 'Putih',
                'mileage' => 15000,
                'features' => json_encode(['AC', 'Audio System', 'Power Steering', 'Central Lock', 'Airbag']),
            ],
            [
                'brand' => 'Honda',
                'model' => 'Civic',
                'category' => 'Sedan',
                'transmission' => 'manual',
                'fuel_type' => 'bensin',
                'seats' => 5,
                'doors' => 4,
                'year' => 2023,
                'engine' => '1.5L Turbo',
                'price_per_day' => 400000,
                'reduce' => 5,
                'police_number' => 'B 2345 DEF',
                'image' => '/storage/cars/Honda_Civic.jpg',
                'status' => 'tersedia',
                'stars' => 4.7,
                'minimum_rental_days' => 1,
                'description' => 'Honda Civic sporty dan efisien untuk perjalanan harian.',
                'color' => 'Merah',
                'mileage' => 8000,
                'features' => json_encode(['AC', 'Audio System', 'Power Window', 'Airbag']),
            ],
            [
                'brand' => 'BMW',
                'model' => 'X5',
                'category' => 'SUV',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 7,
                'doors' => 4,
                'year' => 2023,
                'engine' => '3.0L TwinPower Turbo',
                'price_per_day' => 1200000,
                'reduce' => 15,
                'police_number' => 'B 3456 GHI',
                'image' => '/storage/cars/BMW_X5.jpg',
                'status' => 'tersedia',
                'stars' => 4.9,
                'minimum_rental_days' => 1,
                'description' => 'BMW X5 SUV mewah dengan teknologi terkini dan kenyamanan premium.',
                'color' => 'Hitam',
                'mileage' => 12000,
                'features' => json_encode(['AC', 'Audio System', 'Leather Seat', 'Cruise Control', 'Parking Sensor', 'Sunroof']),
            ],
            [
                'brand' => 'Mercedes-Benz',
                'model' => 'E-Class',
                'category' => 'Sedan',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 5,
                'doors' => 4,
                'year' => 2024,
                'engine' => '2.0L Turbo',
                'price_per_day' => 1500000,
                'reduce' => 0,
                'police_number' => 'B 4567 JKL',
                'image' => '/storage/cars/Mercedes-Benz_E-Class.jpg',
                'status' => 'tersedia',
                'stars' => 5.0,
                'minimum_rental_days' => 1,
                'description' => 'Mercedes-Benz E-Class sedan premium dengan kemewahan tingkat tinggi.',
                'color' => 'Silver',
                'mileage' => 5000,
                'features' => json_encode(['AC', 'Audio System', 'Leather Seat', 'Sunroof', 'Parking Camera', 'Cruise Control', 'Airbag']),
            ],
            [
                'brand' => 'Audi',
                'model' => 'A4',
                'category' => 'Sedan',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 5,
                'doors' => 4,
                'year' => 2023,
                'engine' => '2.0L TFSI',
                'price_per_day' => 950000,
                'reduce' => 10,
                'police_number' => 'B 5678 MNO',
                'image' => '/storage/cars/Audi_A4.jpg',
                'status' => 'tersedia',
                'stars' => 4.8,
                'minimum_rental_days' => 1,
                'description' => 'Audi A4 kombinasi sempurna antara performa dan efisiensi.',
                'color' => 'Abu-abu',
                'mileage' => 18000,
                'features' => json_encode(['AC', 'Audio System', 'Power Window', 'Central Lock', 'Cruise Control']),
            ],
            [
                'brand' => 'Audi',
                'model' => 'Q5',
                'category' => 'SUV',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 5,
                'doors' => 4,
                'year' => 2023,
                'engine' => '2.0L TFSI',
                'price_per_day' => 1100000,
                'reduce' => 0,
                'police_number' => 'B 6789 PQR',
                'image' => '/storage/cars/Audi_Q5.jpg',
                'status' => 'tersedia',
                'stars' => 4.7,
                'minimum_rental_days' => 1,
                'description' => 'Audi Q5 SUV kompak dengan desain elegan dan performa tinggi.',
                'color' => 'Putih Mutiara',
                'mileage' => 10000,
                'features' => json_encode(['AC', 'Audio System', 'Leather Seat', 'Parking Sensor', 'Sunroof']),
            ],
            [
                'brand' => 'Ford',
                'model' => 'Mustang',
                'category' => 'Sedan',
                'transmission' => 'manual',
                'fuel_type' => 'bensin',
                'seats' => 4,
                'doors' => 2,
                'year' => 2024,
                'engine' => '5.0L V8',
                'price_per_day' => 1800000,
                'reduce' => 0,
                'police_number' => 'B 7890 STU',
                'image' => '/storage/cars/Ford_Mustang.jpg',
                'status' => 'tersedia',
                'stars' => 4.9,
                'minimum_rental_days' => 2,
                'description' => 'Ford Mustang muscle car ikonik dengan performa mesin yang powerful.',
                'color' => 'Kuning',
                'mileage' => 5000,
                'features' => json_encode(['AC', 'Audio System', 'Leather Seat', 'Sport Mode']),
            ],
            [
                'brand' => 'Ford',
                'model' => 'Explorer',
                'category' => 'SUV',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 7,
                'doors' => 4,
                'year' => 2023,
                'engine' => '3.0L EcoBoost',
                'price_per_day' => 850000,
                'reduce' => 5,
                'police_number' => 'B 8901 VWX',
                'image' => '/storage/cars/Ford_Explorer.jpg',
                'status' => 'tersedia',
                'stars' => 4.6,
                'minimum_rental_days' => 1,
                'description' => 'Ford Explorer SUV keluarga dengan ruang kabin yang luas.',
                'color' => 'Biru Tua',
                'mileage' => 22000,
                'features' => json_encode(['AC', 'Audio System', 'Power Window', 'Central Lock', 'Parking Sensor']),
            ],
            [
                'brand' => 'Ford',
                'model' => 'Focus',
                'category' => 'Hatchback',
                'transmission' => 'manual',
                'fuel_type' => 'bensin',
                'seats' => 5,
                'doors' => 4,
                'year' => 2022,
                'engine' => '2.0L I4',
                'price_per_day' => 350000,
                'reduce' => 0,
                'police_number' => 'B 9012 YZA',
                'image' => '/storage/cars/Ford_Focus.jpg',
                'status' => 'tersedia',
                'stars' => 4.5,
                'minimum_rental_days' => 1,
                'description' => 'Ford Focus hatchback kompak ideal untuk perjalanan kota.',
                'color' => 'Merah',
                'mileage' => 30000,
                'features' => json_encode(['AC', 'Audio System', 'Power Steering', 'Central Lock']),
            ],
            [
                'brand' => 'Chevrolet',
                'model' => 'Camaro',
                'category' => 'Sedan',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 4,
                'doors' => 2,
                'year' => 2024,
                'engine' => '6.2L V8',
                'price_per_day' => 1600000,
                'reduce' => 10,
                'police_number' => 'B 0123 BCD',
                'image' => '/storage/cars/Chevrolet_Camaro.jpg',
                'status' => 'tersedia',
                'stars' => 4.8,
                'minimum_rental_days' => 2,
                'description' => 'Chevrolet Camaro sports car dengan desain agresif dan performa tinggi.',
                'color' => 'Hitam',
                'mileage' => 7000,
                'features' => json_encode(['AC', 'Audio System', 'Leather Seat', 'Sport Mode', 'Cruise Control']),
            ],
            [
                'brand' => 'Chevrolet',
                'model' => 'Malibu',
                'category' => 'Sedan',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 5,
                'doors' => 4,
                'year' => 2023,
                'engine' => '1.5L Turbo',
                'price_per_day' => 500000,
                'reduce' => 0,
                'police_number' => 'B 1234 EFG',
                'image' => '/storage/cars/Chevrolet_Malibu.jpg',
                'status' => 'tersedia',
                'stars' => 4.6,
                'minimum_rental_days' => 1,
                'description' => 'Chevrolet Malibu sedan mid-size dengan interior yang nyaman.',
                'color' => 'Silver',
                'mileage' => 14000,
                'features' => json_encode(['AC', 'Audio System', 'Power Window', 'Central Lock', 'Airbag']),
            ],
            [
                'brand' => 'Chevrolet',
                'model' => 'Tahoe',
                'category' => 'SUV',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 8,
                'doors' => 4,
                'year' => 2024,
                'engine' => '5.3L V8',
                'price_per_day' => 1300000,
                'reduce' => 5,
                'police_number' => 'B 2345 HIJ',
                'image' => '/storage/cars/Chevrolet_Tahoe.jpg',
                'status' => 'tersedia',
                'stars' => 4.7,
                'minimum_rental_days' => 1,
                'description' => 'Chevrolet Tahoe SUV besar dengan kapasitas penumpang maksimal.',
                'color' => 'Putih',
                'mileage' => 9000,
                'features' => json_encode(['AC', 'Audio System', 'Leather Seat', 'Parking Camera', 'Third Row Seat']),
            ],
            [
                'brand' => 'Nissan',
                'model' => 'Altima',
                'category' => 'Sedan',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 5,
                'doors' => 4,
                'year' => 2023,
                'engine' => '2.5L I4',
                'price_per_day' => 420000,
                'reduce' => 0,
                'police_number' => 'B 3456 KLM',
                'image' => '/storage/cars/Nissan_Altima.jpg',
                'status' => 'tersedia',
                'stars' => 4.5,
                'minimum_rental_days' => 1,
                'description' => 'Nissan Altima sedan dengan desain modern dan teknologi canggih.',
                'color' => 'Abu-abu Metalik',
                'mileage' => 16000,
                'features' => json_encode(['AC', 'Audio System', 'Power Window', 'Airbag', 'Cruise Control']),
            ],
            [
                'brand' => 'Hyundai',
                'model' => 'Sonata',
                'category' => 'Sedan',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 5,
                'doors' => 4,
                'year' => 2023,
                'engine' => '2.5L GDI',
                'price_per_day' => 430000,
                'reduce' => 5,
                'police_number' => 'B 4567 NOP',
                'image' => '/storage/cars/Hyundai_Sonata.jpg',
                'status' => 'tersedia',
                'stars' => 4.6,
                'minimum_rental_days' => 1,
                'description' => 'Hyundai Sonata sedan elegan dengan fitur keselamatan lengkap.',
                'color' => 'Putih',
                'mileage' => 11000,
                'features' => json_encode(['AC', 'Audio System', 'Power Window', 'Airbag', 'Central Lock']),
            ],
            [
                'brand' => 'Hyundai',
                'model' => 'Tucson',
                'category' => 'SUV',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 5,
                'doors' => 4,
                'year' => 2024,
                'engine' => '2.5L GDI',
                'price_per_day' => 650000,
                'reduce' => 10,
                'police_number' => 'B 5678 QRS',
                'image' => '/storage/cars/Hyundai_Tucson.jpg',
                'status' => 'tersedia',
                'stars' => 4.7,
                'minimum_rental_days' => 1,
                'description' => 'Hyundai Tucson SUV kompak dengan desain futuristik.',
                'color' => 'Merah',
                'mileage' => 6000,
                'features' => json_encode(['AC', 'Audio System', 'Power Window', 'Parking Camera', 'Cruise Control']),
            ],
            [
                'brand' => 'Kia',
                'model' => 'Optima',
                'category' => 'Sedan',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 5,
                'doors' => 4,
                'year' => 2023,
                'engine' => '2.0L Turbo',
                'price_per_day' => 410000,
                'reduce' => 0,
                'police_number' => 'B 6789 TUV',
                'image' => '/storage/cars/Kia_Optima.jpg',
                'status' => 'tersedia',
                'stars' => 4.5,
                'minimum_rental_days' => 1,
                'description' => 'Kia Optima sedan dengan performa andal dan harga terjangkau.',
                'color' => 'Hitam',
                'mileage' => 19000,
                'features' => json_encode(['AC', 'Audio System', 'Power Steering', 'Central Lock']),
            ],
            [
                'brand' => 'Mazda',
                'model' => 'CX-5',
                'category' => 'Crossover',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 5,
                'doors' => 4,
                'year' => 2024,
                'engine' => '2.5L Skyactiv',
                'price_per_day' => 700000,
                'reduce' => 5,
                'police_number' => 'B 7890 WXY',
                'image' => '/storage/cars/Mazda_CX-5.jpg',
                'status' => 'tersedia',
                'stars' => 4.8,
                'minimum_rental_days' => 1,
                'description' => 'Mazda CX-5 crossover dengan handling responsif dan desain sporty.',
                'color' => 'Biru Metalik',
                'mileage' => 8500,
                'features' => json_encode(['AC', 'Audio System', 'Power Window', 'Cruise Control', 'Parking Sensor']),
            ],
            [
                'brand' => 'Subaru',
                'model' => 'Impreza',
                'category' => 'Sedan',
                'transmission' => 'manual',
                'fuel_type' => 'bensin',
                'seats' => 5,
                'doors' => 4,
                'year' => 2023,
                'engine' => '2.0L Boxer',
                'price_per_day' => 480000,
                'reduce' => 0,
                'police_number' => 'B 8901 ZAB',
                'image' => '/storage/cars/Subaru_Impreza.jpg',
                'status' => 'tersedia',
                'stars' => 4.6,
                'minimum_rental_days' => 1,
                'description' => 'Subaru Impreza sedan dengan AWD system untuk performa optimal.',
                'color' => 'Biru',
                'mileage' => 17000,
                'features' => json_encode(['AC', 'Audio System', 'Power Window', 'AWD System', 'Airbag']),
            ],
            [
                'brand' => 'Volkswagen',
                'model' => 'Golf',
                'category' => 'Hatchback',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 5,
                'doors' => 4,
                'year' => 2023,
                'engine' => '1.4L TSI',
                'price_per_day' => 520000,
                'reduce' => 10,
                'police_number' => 'B 9012 CDE',
                'image' => '/storage/cars/Volkswagen_Golf.jpg',
                'status' => 'tersedia',
                'stars' => 4.7,
                'minimum_rental_days' => 1,
                'description' => 'Volkswagen Golf hatchback legendaris dengan kualitas build premium.',
                'color' => 'Abu-abu',
                'mileage' => 13000,
                'features' => json_encode(['AC', 'Audio System', 'Power Window', 'Central Lock', 'Airbag']),
            ],
            [
                'brand' => 'Lexus',
                'model' => 'RX 350',
                'category' => 'SUV',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 5,
                'doors' => 4,
                'year' => 2024,
                'engine' => '3.5L V6',
                'price_per_day' => 1400000,
                'reduce' => 0,
                'police_number' => 'B 0123 FGH',
                'image' => '/storage/cars/Lexus_RX_350.jpg',
                'status' => 'tersedia',
                'stars' => 4.9,
                'minimum_rental_days' => 1,
                'description' => 'Lexus RX 350 luxury SUV dengan kenyamanan dan ketenangan berkendara.',
                'color' => 'Putih Mutiara',
                'mileage' => 4000,
                'features' => json_encode(['AC', 'Audio System', 'Leather Seat', 'Sunroof', 'Parking Camera', 'Cruise Control', 'Airbag']),
            ],
            [
                'brand' => 'Jeep',
                'model' => 'Wrangler',
                'category' => 'SUV',
                'transmission' => 'manual',
                'fuel_type' => 'bensin',
                'seats' => 5,
                'doors' => 4,
                'year' => 2024,
                'engine' => '3.6L V6',
                'price_per_day' => 950000,
                'reduce' => 5,
                'police_number' => 'B 1234 IJK',
                'image' => '/storage/cars/Jeep_Wrangler.jpg',
                'status' => 'tersedia',
                'stars' => 4.8,
                'minimum_rental_days' => 1,
                'description' => 'Jeep Wrangler off-road icon untuk petualangan ekstrem.',
                'color' => 'Hijau Army',
                'mileage' => 20000,
                'features' => json_encode(['AC', 'Audio System', '4WD System', 'Off-Road Package']),
            ],
            [
                'brand' => 'Land Rover',
                'model' => 'Range Rover Sport',
                'category' => 'SUV',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 7,
                'doors' => 4,
                'year' => 2024,
                'engine' => '3.0L Supercharged',
                'price_per_day' => 2000000,
                'reduce' => 0,
                'police_number' => 'B 2345 LMN',
                'image' => '/storage/cars/Land_Rover_Range_Rover_Sport.jpg',
                'status' => 'tersedia',
                'stars' => 5.0,
                'minimum_rental_days' => 2,
                'description' => 'Range Rover Sport ultimate luxury SUV dengan kemampuan off-road terbaik.',
                'color' => 'Hitam',
                'mileage' => 3000,
                'features' => json_encode(['AC', 'Audio System', 'Leather Seat', 'Sunroof', 'Parking Camera', 'Terrain Response', 'Airbag']),
            ],
            [
                'brand' => 'Porsche',
                'model' => '911 Carrera',
                'category' => 'Sedan',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 2,
                'doors' => 2,
                'year' => 2024,
                'engine' => '3.0L Twin-Turbo',
                'price_per_day' => 3500000,
                'reduce' => 0,
                'police_number' => 'B 3456 OPQ',
                'image' => '/storage/cars/Porsche_911_Carrera.jpg',
                'status' => 'tersedia',
                'stars' => 5.0,
                'minimum_rental_days' => 3,
                'description' => 'Porsche 911 Carrera supercar legendaris dengan performa luar biasa.',
                'color' => 'Merah',
                'mileage' => 2000,
                'features' => json_encode(['AC', 'Audio System', 'Leather Seat', 'Sport Mode', 'Racing Package']),
            ],
            [
                'brand' => 'Jaguar',
                'model' => 'F-Type',
                'category' => 'Sedan',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 2,
                'doors' => 2,
                'year' => 2024,
                'engine' => '5.0L V8',
                'price_per_day' => 2800000,
                'reduce' => 10,
                'police_number' => 'B 4567 RST',
                'image' => '/storage/cars/Jaguar_F-Type.jpg',
                'status' => 'tersedia',
                'stars' => 4.9,
                'minimum_rental_days' => 2,
                'description' => 'Jaguar F-Type sports car dengan desain British yang elegan.',
                'color' => 'Biru Metalik',
                'mileage' => 4500,
                'features' => json_encode(['AC', 'Audio System', 'Leather Seat', 'Sport Mode', 'Convertible']),
            ],
            [
                'brand' => 'Tesla',
                'model' => 'Model 3',
                'category' => 'Sedan',
                'transmission' => 'automatic',
                'fuel_type' => 'elektrik',
                'seats' => 5,
                'doors' => 4,
                'year' => 2024,
                'engine' => 'Electric Motor',
                'price_per_day' => 1100000,
                'reduce' => 15,
                'police_number' => 'B 5678 UVW',
                'image' => '/storage/cars/Tesla_Model_3.jpg',
                'status' => 'tersedia',
                'stars' => 4.9,
                'minimum_rental_days' => 1,
                'description' => 'Tesla Model 3 mobil listrik dengan teknologi autopilot canggih.',
                'color' => 'Putih',
                'mileage' => 12000,
                'features' => json_encode(['AC', 'Audio System', 'Autopilot', 'Glass Roof', 'Touchscreen Display']),
            ],
            [
                'brand' => 'Volvo',
                'model' => 'XC60',
                'category' => 'SUV',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 5,
                'doors' => 4,
                'year' => 2024,
                'engine' => '2.0L Turbo',
                'price_per_day' => 1250000,
                'reduce' => 0,
                'police_number' => 'B 6789 XYZ',
                'image' => '/storage/cars/Volvo_XC60.jpg',
                'status' => 'tersedia',
                'stars' => 4.8,
                'minimum_rental_days' => 1,
                'description' => 'Volvo XC60 SUV dengan standar keselamatan tertinggi.',
                'color' => 'Abu-abu',
                'mileage' => 7000,
                'features' => json_encode(['AC', 'Audio System', 'Leather Seat', 'Safety Assist', 'Parking Camera', 'Airbag']),
            ],
            [
                'brand' => 'Mitsubishi',
                'model' => 'Outlander',
                'category' => 'SUV',
                'transmission' => 'automatic',
                'fuel_type' => 'bensin',
                'seats' => 7,
                'doors' => 4,
                'year' => 2023,
                'engine' => '2.4L MIVEC',
                'price_per_day' => 600000,
                'reduce' => 5,
                'police_number' => 'B 7890 ABC',
                'image' => '/storage/cars/Mitsubishi_Outlander.jpg',
                'status' => 'tersedia',
                'stars' => 4.5,
                'minimum_rental_days' => 1,
                'description' => 'Mitsubishi Outlander SUV keluarga dengan harga terjangkau.',
                'color' => 'Putih',
                'mileage' => 25000,
                'features' => json_encode(['AC', 'Audio System', 'Power Window', 'Third Row Seat', 'Central Lock']),
            ],
            [
                'brand' => 'Mini',
                'model' => 'Cooper',
                'category' => 'City Car',
                'transmission' => 'manual',
                'fuel_type' => 'bensin',
                'seats' => 4,
                'doors' => 2,
                'year' => 2023,
                'engine' => '1.5L Turbo',
                'price_per_day' => 550000,
                'reduce' => 0,
                'police_number' => 'B 8901 DEF',
                'image' => '/storage/cars/Mini_Cooper.jpg',
                'status' => 'tersedia',
                'stars' => 4.7,
                'minimum_rental_days' => 1,
                'description' => 'Mini Cooper city car ikonik dengan handling gesit.',
                'color' => 'Merah',
                'mileage' => 18000,
                'features' => json_encode(['AC', 'Audio System', 'Sport Mode', 'Compact Design']),
            ],
            [
                'brand' => 'Fiat',
                'model' => '500',
                'category' => 'City Car',
                'transmission' => 'manual',
                'fuel_type' => 'bensin',
                'seats' => 4,
                'doors' => 2,
                'year' => 2022,
                'engine' => '1.2L',
                'price_per_day' => 320000,
                'reduce' => 10,
                'police_number' => 'B 9012 GHI',
                'image' => '/storage/cars/Fiat_500.jpg',
                'status' => 'tersedia',
                'stars' => 4.4,
                'minimum_rental_days' => 1,
                'description' => 'Fiat 500 city car kompak dengan gaya retro modern.',
                'color' => 'Kuning',
                'mileage' => 28000,
                'features' => json_encode(['AC', 'Audio System', 'Power Steering', 'Compact Design']),
            ],
            [
                'brand' => 'GMC',
                'model' => 'Sierra 1500',
                'category' => 'Double Cabin',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'seats' => 5,
                'doors' => 4,
                'year' => 2024,
                'engine' => '3.0L Turbo Diesel',
                'price_per_day' => 1100000,
                'reduce' => 0,
                'police_number' => 'B 0123 JKL',
                'image' => '/storage/cars/GMC_Sierra_1500.jpg',
                'status' => 'tersedia',
                'stars' => 4.7,
                'minimum_rental_days' => 1,
                'description' => 'GMC Sierra 1500 pickup truck dengan daya angkut besar.',
                'color' => 'Hitam',
                'mileage' => 15000,
                'features' => json_encode(['AC', 'Audio System', 'Power Window', 'Cargo Bed', 'Towing Package']),
            ],
        ];

        foreach ($cars as $car) {
            DB::table('cars')->insert(array_merge($car, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        echo "\n✅ Database berhasil di-reset!\n";
        echo "📊 Total mobil: " . count($cars) . "\n";
        echo "👤 Admin: admin@rentcar.com / admin123\n";
        echo "👥 User: user@rentcar.com / user123\n";
        }
    }